name: Build and Push Docker Image

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - maaster

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or any other Docker registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t kishorer772/image-compressor:latest .

      # Step 5: Push Docker image to Docker Hub (optional)
      - name: Push Docker image
        run: |
          docker push kishorer772/image-compressor:latest
